packages:
  - 'packages/*'
  - 'apps/*'

shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

patchedDependencies:
  'tsup@8.5.1': patches/tsup@8.5.1.patch

catalog:
  'tailwindcss-primeui': ^0.6.1
  'primeicons': ^7.0.0

catalogs:
  angular21:
    "@angular-devkit/build-angular": ^22.0.0
    "@angular/animations": ^22.0.0
    "@angular/cdk": ^22.0.0
    "@angular/cli": ^22.0.0
    "@angular/common": ^22.0.0
    "@angular/compiler": ^22.0.0
    "@angular/compiler-cli": ^22.0.0
    "@angular/core": ^22.0.0
    "@angular/forms": ^22.0.0
    "@angular/platform-browser": ^22.0.0
    "@angular/platform-browser-dynamic": ^22.0.0
    "@angular/platform-server": ^22.0.0
    "@angular/router": ^22.0.0
    "@angular/ssr": ^22.0.0
    "@angular-eslint/eslint-plugin": ^20.6.0
    "@angular-eslint/eslint-plugin-template": ^20.6.0
    "@angular-eslint/schematics": ^20.6.0
    "@angular-eslint/template-parser": ^20.6.0
    "ng-packagr": ^22.0.0
    "typescript": ^6.0.0

minimumReleaseAgeExclude:
  - pnpm@11.13.1
