packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/tailwind-playgrounds/*'

shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lefthook: true
  lmdb: true
  msgpackr-extract: true

catalog:
  '@openng/icons': ^1.0.0

catalogs:
  angular22:
    "@angular-devkit/build-angular": ^22.1.4
    "@angular/animations": ^22.1.2
    "@angular/build": ^22.1.4
    "@angular/cdk": ^22.1.2
    "@angular/cli": ^22.1.4
    "@angular/common": ^22.1.2
    "@angular/compiler": ^22.1.2
    "@angular/compiler-cli": ^22.1.2
    "@angular/core": ^22.1.2
    "@angular/forms": ^22.1.2
    "@angular/platform-browser": ^22.1.2
    "@angular/platform-browser-dynamic": ^22.1.2
    "@angular/platform-server": ^22.1.2
    "@angular/router": ^22.1.2
    "@angular/ssr": ^22.1.4
    "@angular-eslint/eslint-plugin": ^22.1.0
    "@angular-eslint/eslint-plugin-template": ^22.1.0
    "@angular-eslint/schematics": ^22.1.0
    "@angular-eslint/template-parser": ^22.1.0
    "ng-packagr": ^22.1.1
    "typescript": ^6.0.0

minimumReleaseAgeExclude:
  - pnpm@11.13.1
  - '@openng/icons@1.0.0'
  - tsdown@0.22.9
