/**
 * Shape of `manifest.json`, generated by `apps/docs/scripts/build-manifest.mjs` (schema version 1).
 */
export interface Manifest {
    schemaVersion: number;
    package: string;
    version: string;
    site: string;
    components: ComponentPage[];
    guides: GuidePage[];
    entryPoints: EntryPoint[];
}

export interface Section {
    id: string;
    label: string;
    description?: string;
    examples?: { typescript?: string; data?: string; scss?: string; command?: string };
}

export interface ComponentPage {
    name: string;
    title: string;
    description: string;
    url: string;
    markdown: string;
    entryPoints?: string[];
    api?: string[];
    /** Services and types the page uses from other entry points, with their import path. */
    related?: { name: string; kind: string; import: string }[];
    sections?: Section[];
    /** Design tokens of the component, as documented in @openng/optimus-ui-themes/tokens. */
    tokens?: { name: string; variable: string; description?: string }[];
}

export interface GuidePage {
    name: string;
    title: string;
    description: string;
    url: string;
    markdown: string;
    sections?: Section[];
}

export interface EntryPoint {
    name: string;
    import: string;
    description?: string;
    docs?: string;
    modules?: string[];
    services?: string[];
    declarations?: Declaration[];
    classes?: TypeDefinition[];
    types?: TypeDefinition[];
    cssClasses?: { class: string; description?: string }[];
}

export interface Declaration {
    kind: 'component' | 'directive';
    className: string;
    selector: string;
    exportAs?: string[];
    standalone?: boolean;
    description?: string;
    deprecated?: string | true;
    inputs?: Input[];
    outputs?: Output[];
    templates?: { name: string; context?: string; description?: string }[];
    methods?: { name: string; parameters?: { name: string; type?: string; description?: string }[]; returnType?: string; description?: string }[];
    forms?: boolean;
    contentProjection?: string[];
    passThrough?: { name: string; type?: string; description?: string }[];
}

export interface Input {
    name: string;
    property?: string;
    type?: string;
    values?: (string | number)[];
    default?: string;
    required?: boolean;
    twoWay?: boolean;
    signal?: boolean;
    transform?: string;
    hostDirective?: string;
    description?: string;
    deprecated?: string | true;
}

export interface Output {
    name: string;
    payload?: string;
    description?: string;
    deprecated?: string | true;
}

export interface TypeDefinition {
    kind: 'interface' | 'type' | 'class';
    name: string;
    description?: string;
    deprecated?: string | true;
    definition?: string;
    values?: (string | number)[];
    properties?: { name: string; type?: string; optional?: boolean; description?: string; deprecated?: string | true }[];
    members?: { name: string; kind: 'method' | 'property'; type?: string; description?: string; deprecated?: string | true }[];
}
