import { Rule, SchematicContext, SchematicsException, Tree } from '@angular-devkit/schematics';
import { NodePackageInstallTask } from '@angular-devkit/schematics/tasks';
import { createIgnoreMatcher, IgnoreMatcher } from '../utils/gitignore';
import { mapAssetReference, SPECIFIER_RENAMES } from '../utils/mappings';
import { findPrimengMajor, SKIP_DIRS, swapDependencies } from '../utils/package-json';
import { renameStylesheetLayers, rewriteSource } from '../utils/rewrite';
import { Schema } from './schema';

const REPORT_EXTENSIONS = ['.ts', '.mts', '.js', '.mjs', '.html', '.scss', '.css', '.sass', '.less', '.json', '.md'];
// Files where renamed package assets (SPECIFIER_RENAMES) are referenced by path rather than
// imported: global stylesheets and the styles arrays of angular.json/project.json.
const STYLESHEET_EXTENSIONS = ['.css', '.scss', '.sass', '.less'];
const WORKSPACE_CONFIG_NAMES = new Set(['angular.json', 'project.json']);
const TAILWIND_CONFIG_RE = /(^|\/)tailwind\.config\.(js|cjs|mjs)$/;
// A quoted string that follows an at-rule keyword: `@import 'pkg'`, `@use 'pkg/file'`,
// `@plugin "pkg"`, `@reference`, `@config`, `@source`. Declaration values such as
// `font-family: 'primeicons'` are deliberately out of reach — they are not package references.
const STYLE_AT_RULE_RE = /(@[a-zA-Z-]+\s+)(['"])([^'"\n]+)\2/g;
// `url(pkg/file)`, with or without quotes.
const URL_REFERENCE_RE = /\burl\(\s*(['"]?)([^)'"\n]+)\1\s*\)/g;
// Every string in angular.json/project.json styles/scripts arrays is a path.
const JSON_STRING_RE = /"([^"\n]+)"/g;
const MIN_PRIMENG_MAJOR = 21;
// Lockfiles are regenerated by the scheduled NodePackageInstallTask and would otherwise flood the
// leftover report with dozens of registry URL lines for a dependency we already swapped out.
const LOCKFILE_NAMES = new Set(['package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb', 'bun.lock']);

export function migrateFromPrimeng(options: Schema): Rule {
    return (tree: Tree, context: SchematicContext) => {
        checkVersionGate(tree, options);

        // Coverage reports, build output and other git-ignored files are not the user's source:
        // rewriting them is pointless and reporting them buries the leftovers that do matter.
        const isIgnored = createIgnoreMatcher(tree);

        const packageJsonPaths: string[] = [];
        const sourcePaths: string[] = [];
        const assetReferencePaths: string[] = [];
        tree.visit((path) => {
            if (SKIP_DIRS.test(path) || isIgnored(path)) {
                return;
            }
            const basename = path.slice(path.lastIndexOf('/') + 1);
            if (basename === 'package.json') {
                packageJsonPaths.push(path);
            } else if (path.endsWith('.ts') || path.endsWith('.mts') || TAILWIND_CONFIG_RE.test(path)) {
                sourcePaths.push(path);
            } else if (STYLESHEET_EXTENSIONS.some((ext) => path.endsWith(ext)) || WORKSPACE_CONFIG_NAMES.has(basename)) {
                assetReferencePaths.push(path);
            }
        });

        for (const path of packageJsonPaths) {
            migratePackageJson(tree, context, path);
        }
        // Layer tokens renamed inside cssLayer name/order strings (e.g. primeng-overwrites →
        // optimus-overwrites), collected across all sources so the matching `@layer` declarations
        // in stylesheets can be renamed to keep following the configured order.
        const layerRenames = new Map<string, string>();
        for (const path of sourcePaths) {
            const original = tree.read(path)!.toString();
            const { text, changed, layerRenames: fileLayerRenames } = rewriteSource(path, original);
            for (const [from, to] of fileLayerRenames) {
                layerRenames.set(from, to);
            }
            if (changed) {
                tree.overwrite(path, text);
            }
        }
        for (const path of assetReferencePaths) {
            migrateAssetReferences(tree, path, layerRenames);
        }

        reportLeftovers(tree, context, isIgnored);

        if (!options.skipInstall) {
            context.addTask(new NodePackageInstallTask());
        }
        return tree;
    };
}

function checkVersionGate(tree: Tree, options: Schema): void {
    if (options.force) {
        return;
    }
    const major = findPrimengMajor(tree);
    if (major === null) {
        throw new SchematicsException('primeng is not installed in this workspace (or its version could not be parsed). Use --force to run the code migration anyway.');
    }
    if (major < MIN_PRIMENG_MAJOR) {
        throw new SchematicsException(`Found primeng v${major}. Optimus UI is API-compatible with primeng v21 — upgrade first (ng update primeng@21), then re-run this migration. Use --force to skip this check.`);
    }
}

function migratePackageJson(tree: Tree, context: SchematicContext, path: string): void {
    const raw = tree.read(path)!.toString();
    const pkg = JSON.parse(raw);
    const result = swapDependencies(pkg);
    if (!result.changed) {
        return;
    }
    const indent = raw.match(/^\{\r?\n(\s+)/)?.[1] ?? '    ';
    tree.overwrite(path, JSON.stringify(pkg, null, indent) + '\n');
    context.logger.info(`${path}: replaced ${result.removed.join(', ')} with ${result.added.join(', ')}`);
}

function migrateAssetReferences(tree: Tree, path: string, layerRenames: ReadonlyMap<string, string>): void {
    let text = tree.read(path)!.toString();
    let changed = false;
    for (const [from, to] of SPECIFIER_RENAMES) {
        if (text.includes(from)) {
            text = text.split(from).join(to);
            changed = true;
        }
    }
    const rewrite = (reference: string, rebuild: (mapped: string) => string, match: string): string => {
        const mapped = mapAssetReference(reference);
        if (mapped === null) {
            return match;
        }
        changed = true;
        return rebuild(mapped);
    };
    if (WORKSPACE_CONFIG_NAMES.has(path.slice(path.lastIndexOf('/') + 1))) {
        text = text.replace(JSON_STRING_RE, (match, value: string) => rewrite(value, (mapped) => `"${mapped}"`, match));
    } else {
        text = text.replace(STYLE_AT_RULE_RE, (match, rule: string, quote: string, value: string) => rewrite(value, (mapped) => `${rule}${quote}${mapped}${quote}`, match));
        text = text.replace(URL_REFERENCE_RE, (match, quote: string, value: string) => rewrite(value, (mapped) => `url(${quote}${mapped}${quote})`, match));
        const layered = renameStylesheetLayers(text, layerRenames);
        if (layered.changed) {
            text = layered.text;
            changed = true;
        }
    }
    if (changed) {
        tree.overwrite(path, text);
    }
}

function isLockfile(path: string): boolean {
    const basename = path.slice(path.lastIndexOf('/') + 1);
    return LOCKFILE_NAMES.has(basename);
}

const MIGRATION_GUIDE_URL = 'https://www.openng.org/migration/primeng';

function reportLeftovers(tree: Tree, context: SchematicContext, isIgnored: IgnoreMatcher): void {
    const leftovers: string[] = [];
    const files = new Set<string>();
    tree.visit((path, entry) => {
        if (SKIP_DIRS.test(path) || !entry || isLockfile(path) || isIgnored(path) || !REPORT_EXTENSIONS.some((ext) => path.endsWith(ext))) {
            return;
        }
        entry.content
            .toString()
            .split('\n')
            .forEach((line, index) => {
                if (/primeng|primeicons|@primeuix|tailwindcss-primeui|primelocale/i.test(line)) {
                    leftovers.push(`${path}:${index + 1}  ${line.trim()}`);
                    files.add(path);
                }
            });
    });
    if (leftovers.length === 0) {
        context.logger.info('No leftover primeng/primeicons/@primeuix/tailwindcss-primeui/primelocale references found — nothing left to review.');
        return;
    }
    const summary = `${leftovers.length} reference${leftovers.length === 1 ? '' : 's'} in ${files.size} file${files.size === 1 ? '' : 's'}`;
    context.logger.warn(`The following ${summary} could not be migrated automatically and need manual review:`);
    for (const leftover of leftovers) {
        context.logger.warn(`  ${leftover}`);
    }
    // The CLI prints its CREATE/UPDATE list once the rule returns, which pushes the report above
    // out of sight. Close with a reminder that the file list is not the whole story.
    context.logger.warn(`\nMigration done, but ${summary} still need manual review. Scroll up to the list above — the CREATE/UPDATE lines that follow only cover what was migrated for you.`);
    context.logger.warn(`Manual migration tables: ${MIGRATION_GUIDE_URL}`);
}
