import { Rule, SchematicContext, SchematicsException, Tree } from '@angular-devkit/schematics';
import { NodePackageInstallTask } from '@angular-devkit/schematics/tasks';
import { SPECIFIER_RENAMES } from '../utils/mappings';
import { findPrimengMajor, SKIP_DIRS, swapDependencies } from '../utils/package-json';
import { rewriteSource } from '../utils/rewrite';
import { Schema } from './schema';

const REPORT_EXTENSIONS = ['.ts', '.mts', '.js', '.mjs', '.html', '.scss', '.css', '.sass', '.less', '.json', '.md'];
// Files where renamed package assets (SPECIFIER_RENAMES) are referenced by path rather than
// imported: global stylesheets and the styles arrays of angular.json/project.json.
const STYLESHEET_EXTENSIONS = ['.css', '.scss', '.sass', '.less'];
const WORKSPACE_CONFIG_NAMES = new Set(['angular.json', 'project.json']);
const TAILWIND_CONFIG_RE = /(^|\/)tailwind\.config\.(js|cjs|mjs)$/;
const MIN_PRIMENG_MAJOR = 21;
// Lockfiles are regenerated by the scheduled NodePackageInstallTask and would otherwise flood the
// leftover report with dozens of registry URL lines for a dependency we already swapped out.
const LOCKFILE_NAMES = new Set(['package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb', 'bun.lock']);

export function migrateFromPrimeng(options: Schema): Rule {
    return (tree: Tree, context: SchematicContext) => {
        checkVersionGate(tree, options);

        const packageJsonPaths: string[] = [];
        const sourcePaths: string[] = [];
        const assetReferencePaths: string[] = [];
        tree.visit((path) => {
            if (SKIP_DIRS.test(path)) {
                return;
            }
            const basename = path.slice(path.lastIndexOf('/') + 1);
            if (basename === 'package.json') {
                packageJsonPaths.push(path);
            } else if (path.endsWith('.ts') || path.endsWith('.mts') || TAILWIND_CONFIG_RE.test(path)) {
                sourcePaths.push(path);
            } else if (STYLESHEET_EXTENSIONS.some((ext) => path.endsWith(ext)) || WORKSPACE_CONFIG_NAMES.has(basename)) {
                assetReferencePaths.push(path);
            }
        });

        for (const path of packageJsonPaths) {
            migratePackageJson(tree, context, path);
        }
        for (const path of sourcePaths) {
            const original = tree.read(path)!.toString();
            const { text, changed } = rewriteSource(path, original);
            if (changed) {
                tree.overwrite(path, text);
            }
        }
        for (const path of assetReferencePaths) {
            migrateAssetReferences(tree, path);
        }

        reportLeftovers(tree, context);

        if (!options.skipInstall) {
            context.addTask(new NodePackageInstallTask());
        }
        return tree;
    };
}

function checkVersionGate(tree: Tree, options: Schema): void {
    if (options.force) {
        return;
    }
    const major = findPrimengMajor(tree);
    if (major === null) {
        throw new SchematicsException('primeng is not installed in this workspace (or its version could not be parsed). Use --force to run the code migration anyway.');
    }
    if (major < MIN_PRIMENG_MAJOR) {
        throw new SchematicsException(`Found primeng v${major}. Optimus UI is API-compatible with primeng v21 — upgrade first (ng update primeng@21), then re-run this migration. Use --force to skip this check.`);
    }
}

function migratePackageJson(tree: Tree, context: SchematicContext, path: string): void {
    const raw = tree.read(path)!.toString();
    const pkg = JSON.parse(raw);
    const result = swapDependencies(pkg);
    if (!result.changed) {
        return;
    }
    const indent = raw.match(/^\{\r?\n(\s+)/)?.[1] ?? '    ';
    tree.overwrite(path, JSON.stringify(pkg, null, indent) + '\n');
    context.logger.info(`${path}: replaced ${result.removed.join(', ')} with ${result.added.join(', ')}`);
}

function migrateAssetReferences(tree: Tree, path: string): void {
    let text = tree.read(path)!.toString();
    let changed = false;
    for (const [from, to] of SPECIFIER_RENAMES) {
        if (text.includes(from)) {
            text = text.split(from).join(to);
            changed = true;
        }
    }
    if (changed) {
        tree.overwrite(path, text);
    }
}

function isLockfile(path: string): boolean {
    const basename = path.slice(path.lastIndexOf('/') + 1);
    return LOCKFILE_NAMES.has(basename);
}

function reportLeftovers(tree: Tree, context: SchematicContext): void {
    const leftovers: string[] = [];
    tree.visit((path, entry) => {
        if (SKIP_DIRS.test(path) || !entry || isLockfile(path) || !REPORT_EXTENSIONS.some((ext) => path.endsWith(ext))) {
            return;
        }
        entry.content
            .toString()
            .split('\n')
            .forEach((line, index) => {
                if (/primeng|primeicons|@primeuix|tailwindcss-primeui|primelocale/i.test(line)) {
                    leftovers.push(`${path}:${index + 1}  ${line.trim()}`);
                }
            });
    });
    if (leftovers.length > 0) {
        context.logger.warn('The following references to primeng/primeicons/@primeuix/tailwindcss-primeui/primelocale could not be migrated automatically and need manual review:');
        for (const leftover of leftovers) {
            context.logger.warn(`  ${leftover}`);
        }
    }
}
