import generatedVersions from './versions.json';

export const MODULE_MAP: ReadonlyMap<string, string> = new Map([
    ['primeng', '@openng/optimus-ui'],
    ['primeicons', '@openng/icons'],
    ['@primeuix/themes', '@openng/optimus-ui-themes'],
    ['@primeuix/styled', '@openng/optimus-ui-styled'],
    ['@primeuix/styles', '@openng/optimus-ui-styles'],
    ['@primeuix/utils', '@openng/optimus-ui-utils'],
    ['@primeuix/motion', '@openng/optimus-ui-motion'],
    ['tailwindcss-primeui', '@openng/optimus-ui-tailwindcss'],
    ['primelocale', '@openng/optimus-ui-locale']
]);

// Files that were renamed inside a package, so the prefix mapping alone would produce a
// broken path. Checked before MODULE_MAP for module specifiers, and applied verbatim to
// stylesheets and angular.json/project.json (e.g. "node_modules/primeicons/primeicons.css").
export const SPECIFIER_RENAMES: ReadonlyMap<string, string> = new Map([['primeicons/primeicons.css', '@openng/icons/openng-icons.css']]);

export const IDENTIFIER_RENAMES: ReadonlyMap<string, string> = new Map([
    ['providePrimeNG', 'provideOptimus'],
    ['PrimeNG', 'Optimus'],
    ['PrimeNGConfigType', 'OptimusConfigType'],
    // The icon constants class was renamed alongside the primeicons -> @openng/icons package.
    // @openng/optimus-ui/api keeps a deprecated PrimeIcons alias, so unmigrated code still
    // compiles, but rewriting to OpenngIcons moves users onto the current API.
    ['PrimeIcons', 'OpenngIcons']
]);

// versions.json is generated by scripts/build-schematics.mjs from the workspace package
// manifests (and the pnpm-workspace.yaml catalog for @openng/icons) — never edit it by hand.
export const VERSIONS: Readonly<Record<string, string>> = generatedVersions;

export function mapModuleSpecifier(spec: string): string | null {
    const renamed = SPECIFIER_RENAMES.get(spec);
    if (renamed !== undefined) {
        return renamed;
    }
    for (const [from, to] of MODULE_MAP) {
        if (spec === from) {
            return to;
        }
        if (spec.startsWith(from + '/')) {
            return to + spec.slice(from.length);
        }
    }
    return null;
}
