import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SchematicTestRunner } from '@angular-devkit/schematics/testing';
import { describe, expect, it } from 'vitest';
import { createAppTree, createRunner } from './helpers';

describe('collection smoke', () => {
    it('loads and runs ng-add against a minimal tree', async () => {
        const runner = createRunner();
        const tree = await runner.runSchematic('ng-add', { skipInstall: true }, createAppTree());
        expect(tree.files).toContain('/src/app/app.config.ts');
    });

    it('loads and runs migrate-from-primeng', async () => {
        const runner = createRunner();
        const tree = await runner.runSchematic('migrate-from-primeng', { skipInstall: true, force: true }, createAppTree());
        expect(tree.files).toContain('/package.json');
    });
});

// The published package.json (generated by ng-packagr) declares `"type": "module"`, while tsc
// compiles the schematics to CommonJS. Recreate the published layout — the compiled schematics
// nested under a type:module package — and make sure the collection still loads. Without the
// `{ "type": "commonjs" }` package.json that build-schematics.mjs writes into dist/, Node treats
// the .js files as ES modules and every schematic crashes on load (issue: "exports is not
// defined in ES module scope").
describe('published ESM package scope', () => {
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    const FIXTURE_DIR = path.resolve(__dirname, '../.esm-scope-fixture');

    it('loads the compiled schematics from inside a "type": "module" package', async () => {
        fs.rmSync(FIXTURE_DIR, { recursive: true, force: true });
        fs.cpSync(path.resolve(__dirname, '../dist'), path.join(FIXTURE_DIR, 'schematics'), { recursive: true });
        fs.writeFileSync(path.join(FIXTURE_DIR, 'package.json'), JSON.stringify({ name: 'esm-scope-fixture', version: '0.0.0', type: 'module' }, null, 4) + '\n');
        try {
            const runner = new SchematicTestRunner('optimus-ui', path.join(FIXTURE_DIR, 'schematics/collection.json'));
            const tree = await runner.runSchematic('ng-add', { skipInstall: true }, createAppTree());
            expect(tree.files).toContain('/src/app/app.config.ts');
        } finally {
            fs.rmSync(FIXTURE_DIR, { recursive: true, force: true });
        }
    });
});
