name: PR Title

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Use Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: 24.x
                  cache: 'pnpm'

            - name: Install packages
              run: |
                  pnpm install

            - name: Lint PR title
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                  echo "$PR_TITLE" | pnpm exec commitlint --verbose
