name: PR Title

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup

            - name: Lint PR title
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                  echo "$PR_TITLE" | pnpm exec commitlint --verbose
